AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    NodeCanvasLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: canvas-nodejs
            Description: canvas@2.8.0
            ContentUri: s3://lambda-layer-charoitel/canvas-nodejs_v2.8.0.zip
            CompatibleRuntimes:
                - nodejs14.x
            RetentionPolicy: Retain
            LicenseInfo: MIT
          